### PR TITLE
Typo and link corrections on main landing page

### PR DESCRIPTION
**Pull request by ArthurZey**

### CODE REVIEW

**Comment by shiya** [comment]
Looks good to me.

**Comment by ArthurZey** [comment]
@shiya: I merged in the PR yesterday, but I don't see it reflected on the site yet. I don't have much experience with GitHub pages. What else do I need to do to get the latest version in `master` reflected live?

**Comment by augustogoncalves** [comment]
It needs to rebuild, so I have done it. Should be live now.

**Comment by ArthurZey** [comment]
@augustogoncalves: Thanks! What are the steps to rebuild?

**Comment by shiya** [comment]
@ArthurZey right now, after you cloned the repo and made changes to it just do before pushing the changes.
``` bash
npm run build
```

**Pull request merged**
